//----ADD_PRODUCTS_TO_CART-----
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_RESPONSE = "ADD_TO_CART_RESPONSE";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
