//----ADD_PRODUCTS_TO_CART-----
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_RESPONSE = "ADD_TO_CART_RESPONSE";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

//------GET_CART_PRODUCT---------
export const GET_CART_PRODUCT_REQUEST = "GET_CART_PRODUCT_REQUEST"
export const GET_CART_PRODUCT_RESPONSE = "GET_CART_PRODUCT_RESPONSE"
export const GET_CART_PRODUCT_ERROR = "GET_CART_PRODUCT_ERROR"
